### ISSUE TITLE
勤怠情報が正しくない？

### ISSUE THREAD

**Issue by irok** [irok/kinnosuke-time-recorder#27]
@tosite0345 勤怠情報なんですが、

<img src="https://user-images.githubusercontent.com/899532/55552517-85f88880-5718-11e9-8954-1e265792b2bb.png" width="176"/>

必要な勤務時間には「所定の勤務時間－現在の勤務時間」が入っていますが、有休が考慮されていないようです。
有休分は８時間労働したものとして必要時間から引くようにはできますか？

弊社の場合「実働時間」以外に有休分も入った「勤務時間」というカラムがあるのですが、前に tosite0345 さんがアップしてくれたキャプチャを見るとないんですよね。
となると、休暇の選択を有給か無給かで分けて管理しなければならなくなって煩雑になっちゃうので悩ましいですが。。。

もう１つ、上のキャプチャを見て頂くと「予定過不足時間」が不思議な感じになっています。
分の計算が `time % 60` のようになっているので、time がマイナスだと分もマイナスになってしまうのだと思います。

**Comment by tosite0345** [comment]
@irok さん
検証ありがとうございます。
`time % 60` 問題についてはこちらでも確認が取れており、修正用のプルリクを準備していたところでした。
こちらは早めに出させていただきます。

有給の件、そうだったのですね…！
有給であれば `有給 * 基本勤務時間` として計算するようにしないといけなさそうですね…。
あるいはチェックボックスで「実働時間」 OR 「勤務時間」を選べるようにするか…悩ましいところです。
使い勝手のことを考えると、場合分けして計算するのが良さそうですが、いかがでしょうか？

こちらの対応は少し時間かかるかもしれませんが、対応させていただきます。

**Comment by irok** [comment]
@tosite0345 ありがとうございます。
分がマイナスになってしまう件はよろしくお願いします。

有休への対応ですが、今は「休暇」のカラムを選択させているだけで、有給か無給かは分からないので、ちゃんと対応するにはそれぞれを選択させる必要がありそうですね。
（有休を加味した勤務時間が企業ごとの設定に関係なく取れるといいんですけどね…）

**Comment by tosite0345** [comment]
@irok さん
ひとまず分のレイアウトが崩れる問題については https://github.com/irok/KinnosukeTimeRecorder/pull/28 こちらで解消しました。

対応として、軽く考えてみましたが

1. 休暇のうち有給のものにチェックを入れてもらう
1. 有給を加味した勤務時間にチェックを入れてもらう
1. 実働時間・勤務時間の値を取得し、多い方を実勤務時間とする

のどれかで対応できないかと考えておりました。
3.が割といいかなーと思ったのですが、他の名前で使っている企業様があった場合対応できないなぁ・・・と。

**Comment by irok** [comment]
@tosite0345 さんの会社の場合、「実働時間」が有休分の労働時間を含んでいるんでしょうか？
であれば 3. でよいのかもしれません。
企業によって対応できないかもしれない件については、分からない部分が多くどうしようもないので、この機能はいったんβ扱いとして「正しく表示されていない場合はIssueにご連絡ください。」みたいな文言をオプション画面に記載しておくのでどうでしょうか。

**Comment by irok** [comment]
あと、僕の環境だと「今日の勤務時間」が常に 0:00 になっちゃうんですよね。
コード追ってみたんですが、
https://github.com/irok/KinnosukeTimeRecorder/blob/master/js/ktr.js#L634
ここが問題で、弊社は20日締めなので勤怠テーブルが21日から始まっていて、例えば今日（4/10）だと3/30の行を参照しちゃうんですよ。
ここも「日」のカラムを見て、対象の行を特定しないとダメですね。

**Comment by irok** [comment]
manifest v3対応の際、対応しきれなかったので、機能ごと落としました。m(_ _)m
